name: listenmebaby71_s_application17
description: A new Flutter project.

version: 1.0.2+3

environment: 
  sdk: '>=2.12.0 <3.0.0'



dependencies: 
  flutter: 
    sdk: flutter
  retrofit: '>=4.0.0 <5.0.0'
  syncfusion_flutter_charts: ^21.1.39
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  image_picker:
  sleek_circular_slider:
    path: ./sleek_circular_slider-2.0.1-v2/
  path_provider: ^2.0.15
  flutter_svg_provider: ^1.0.3
  get: ^4.6.5
  intl: ^0.17.0
  hive:
  hive_flutter:
  url_launcher: 6.0.20
  flutter_sound: ^8.1.9
  permission_handler: ^10.2.0
  pie_chart: ^5.3.2
  just_audio:
  audio_video_progress_bar: ^0.9.0
  audio_session: ^0.1.13
  shared_preferences: ^2.1.0
  pdf:
  printing: ^5.11.0
  record: ^4.4.4
  firebase_messaging: ^14.4.1
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.0.0+1
  firebase_auth: ^4.6.3

  google_api_availability: ^5.0.0
  googleapis:
  googleapis_auth:
  file_picker:
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

  yookassa_payments_flutter: ^1.0.6
  uuid: ^3.0.7


dev_dependencies:
  flutter_test: 
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable:

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/pdf/
    - assets/images/recomendations/
    - assets/images/event_images/
    - assets/fonts/
  fonts: 
    - family: Akrobat
      fonts: 
        - asset: assets/fonts/AkrobatBold.ttf
          weight: 700
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayThin.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplayLight.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
