name: sleek_circular_slider
description: A highly customizable circular slider/progress bar & spinner for Flutter.
version: 2.0.1
homepage: https://github.com/matthewfx/sleek-circular-slider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: